[package]
name = "auto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rayon = "1.5.2"

ndarray = {version = "0.15.4", features = ["rayon"]}

rand = "0.8.5"

mnist = "0.4.0"

image = "0.24.2"